import AppLayout from '@/components/layout/AppLayout';
import { MaterialThemeProvider } from '@/providers/MeterialUIProvider';
import { ReactQueryProvider } from '@/providers/ReactQueryProvider';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<ReactQueryProvider>
					<MaterialThemeProvider>
						<AppLayout>{children}</AppLayout>
					</MaterialThemeProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
