import { MaterialThemeProvider } from '@/providers/MeterialUIProvider';
import { ReactQueryProvider } from '@/providers/ReactQueryProvider';
import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<ReactQueryProvider>
				<MaterialThemeProvider>
					<body>{children}</body>
				</MaterialThemeProvider>
			</ReactQueryProvider>
		</html>
	);
}
